backend:
  name: git-gateway
  branch: main

# 媒体文件配置
media_folder: "source/images"
public_folder: "/images"

# 站点信息
site_url: https://cia011.github.io
display_url: https://cia011.github.io

# 集合配置
collections:
  - name: "blog"
    label: "博客文章"
    folder: "source/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "标题", widget: "string" }
      - { name: "date", label: "发布时间", widget: "datetime" }
      - { name: "tags", label: "标签", widget: "list" }
      - { name: "categories", label: "分类", widget: "string" }
      - { name: "body", label: "内容", widget: "markdown" }