backend:
  name: github
  repo: Cia011/blog-source   # 注意：这里用新的源码仓库

media_folder: "source/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "博客文章"
    folder: "source/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "标题", widget: "string" }
      - { name: "date", label: "发布时间", widget: "datetime" }
      - { name: "tags", label: "标签", widget: "list" }
      - { name: "categories", label: "分类", widget: "string" }
      - { name: "body", label: "内容", widget: "markdown" }